#!/bin/bash
# install-hook.sh — Install the security pre-commit hook in the current git repo.
#
# Run from anywhere within the target repo. Generates `.git/hooks/pre-commit`
# pointing to scan.sh in this skill's scripts/ directory (via absolute path).
#
# Idempotent: re-running just overwrites the hook.
#
# Usage:
#   /path/to/skills/tools/security-precommit-check/scripts/install-hook.sh

set -euo pipefail

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SCAN_SH="$SCRIPT_DIR/scan.sh"

if [ ! -f "$SCAN_SH" ]; then
  echo "install-hook.sh: scan.sh not found at $SCAN_SH" >&2
  exit 1
fi

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "install-hook.sh: not inside a git repository" >&2
  exit 1
}

HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"

cat > "$HOOK_PATH" << EOF
#!/bin/bash
# Auto-generated by tools/security-precommit-check/scripts/install-hook.sh
# Calls the central scanner against staged files.
exec "$SCAN_SH" --staged
EOF

chmod +x "$HOOK_PATH"

# Per-repo rules — create empty file with template if missing
PROJECT_RULES="$REPO_ROOT/.security-precommit-rules.txt"
if [ ! -f "$PROJECT_RULES" ]; then
  TEMPLATE="$SCRIPT_DIR/../templates/security-precommit-rules.txt.example"
  if [ -f "$TEMPLATE" ]; then
    cp "$TEMPLATE" "$PROJECT_RULES"
    echo "Created template: $PROJECT_RULES (edit to add per-repo rules)"
  fi
fi

# 🔴 Ignore it, always, in every repo — a denylist of secrets IS a list of secrets.
# This installer used to drop the file in and walk away, so it got committed like any
# other config. In THIS repo that published a Cloudflare-hidden origin IP for ten weeks:
# the rule "never commit the VPS IP" was the thing committing the VPS IP. The file is
# per-machine operator config, not shared project config, so nothing is lost by ignoring
# it — and the sibling samples file holds the same strings, so it goes too.
IGNORE="$REPO_ROOT/.gitignore"
for f in .security-precommit-rules.txt .security-precommit-samples.txt; do
  if ! grep -qxF "$f" "$IGNORE" 2>/dev/null; then
    [ -s "$IGNORE" ] && [ -n "$(tail -c 1 "$IGNORE" 2>/dev/null)" ] && printf '\n' >> "$IGNORE"
    printf '%s\n' "$f" >> "$IGNORE"
    echo "  → .gitignore += $f"
  fi
  # Already tracked from a previous install? Untrack it (content stays on disk).
  if git -C "$REPO_ROOT" ls-files --error-unmatch "$f" >/dev/null 2>&1; then
    git -C "$REPO_ROOT" rm --cached --quiet "$f"
    echo "  🔴 $f was TRACKED — untracked it. If this repo is public, assume the"
    echo "     values in it are already exposed and rotate anything still live."
  fi
done

echo "Installed pre-commit hook → $HOOK_PATH"
echo "  → calls: $SCAN_SH --staged"
echo "  → reads default rules from $SCRIPT_DIR/../rules/default.txt"
echo "  → reads per-repo rules from $PROJECT_RULES (if exists)"
echo
echo "Test it:"
echo "  $SCAN_SH --all"
